services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:1234@mysql:3306/instagram
    depends_on:
      - mysql
    volumes:
      - ./backend:/app/backend
      - ./run.py:/app/run.py
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
      - ./uploads:/app/uploads  # Volumen persistente para las imágenes subidas
    entrypoint: >
      sh -c "
      while ! nc -z mysql 3306; do
        echo 'Esperando a MySQL...';
        sleep 5;
      done;
      python run.py"
    networks:
      - flask_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: instagram
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

volumes:
  mysql_data:
  uploads:  # Volumen para las imágenes subidas

networks:
  flask_network:
